#+TITLE: Kinhung Lam
#+OPTIONS: toc:nil num:nil author:nil
#+OPTIONS: date:nil
#+STARTUP: showall inlineimages

#+BEGIN_resumecontact
linjxljx@gmail.com \bullet
[[https://github.com/davylin/][github]] \bullet
[[https://www.linkedin.cn/incareer/in/davy-lin-4a084260][linkedin]] \bullet
[[https://kinhung.me][homepage]]
#+END_resumecontact

* Profile

I am a programmer at ylkj.com, i have 14 years of
software development experience and 3 years of
marathon running experience.
• I live in Taijiang,FuZhou,FuJian in china.
• My major programming languages are Java/
JavaScript.Also I'm interested in Clojure/Go, Scheme
and Rust etc.
• During past 14 years, I've developed enterprise
applications, web applications, mobile applications
etc.I'm a faithful user of Mac with 10 years of
experience.

* Core Skills
:PROPERTIES:
:HTML_CONTAINER_CLASS: skills
:END:

- Languages :: Extensive professional experience with Java, Rust, Clojure,
  and Ruby. Other work and personal project experience with Python,
  JavaScript.
- Technologies :: Linux, Mac, Docker, Android, iOS, Vertica,
  MySQL, MariaDB.
- Fundamentals :: Network & Web, Stream Processing, Object-Oriented
  Design, Functional Programming, Test-Driven Development,
  Continuous Delivery, Virtualization.

* Work Experience

